apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hdfs-log-anomaly
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/grant0808/HDFS_log_Anomaly_Detection_for_MLOps.git
    targetRevision: main
    path: helm/hdfs-log-anomaly
  destination:
    server: https://kubernetes.default.svc
    namespace: hdfs-observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
