apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hdfs-log-anomaly.name" . }}-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hdfs-log-anomaly.name" . }}-api
  template:
    metadata:
      labels:
        app: {{ include "hdfs-log-anomaly.name" . }}-api
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8000"
    spec:
      serviceAccountName: {{ include "hdfs-log-anomaly.serviceAccountName" . }}
      initContainers:
        - name: model-downloader
          image: google/cloud-sdk:slim
          command: ["sh", "-c"]
          args:
            - |
              echo "Checking if model files exist in GCS..."
              gsutil -q stat gs://${GCS_ARTIFACTS_BUCKET}/models/model.pt
              if [ $? -eq 0 ]; then
                echo "Downloading model artifacts from gs://${GCS_ARTIFACTS_BUCKET}/models/..."
                gsutil cp gs://${GCS_ARTIFACTS_BUCKET}/models/model.pt /shared-artifacts/model.pt
                gsutil cp gs://${GCS_ARTIFACTS_BUCKET}/models/vocab.json /shared-artifacts/vocab.json
              else
                echo "Model artifacts not found in GCS models/ folder. System will start in Fallback Rule mode."
              fi
          env:
            - name: GCS_ARTIFACTS_BUCKET
              value: {{ .Values.env.GCS_ARTIFACTS_BUCKET | quote }}
          volumeMounts:
            - name: shared-model-volume
              mountPath: /shared-artifacts
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
{{ range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{ end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
                optional: true
          volumeMounts:
            - name: shared-model-volume
              mountPath: /app/artifacts
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: shared-model-volume
          emptyDir: {}

