{{- if .Values.streaming.flinkJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hdfs-log-anomaly.name" . }}-flink-submit
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "hdfs-log-anomaly.serviceAccountName" . }}
      containers:
        - name: flink-job
          image: "{{ .Values.streamingImage.repository }}:{{ .Values.streamingImage.tag }}"
          imagePullPolicy: {{ .Values.streamingImage.pullPolicy }}
          command: ["python", "-m", "flink.hdfs_log_job"]
          env:
{{ range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
{{ end }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
                optional: true
{{- end }}
