apiVersion: v1
kind: Service
metadata:
  name: {{ include "hdfs-log-anomaly.name" . }}-api
spec:
  selector:
    app: {{ include "hdfs-log-anomaly.name" . }}-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
